---
- hosts: all
  become: yes

  vars:
    repo_url: "https://github.com/Neleoko/TP-React-Ansible.git"
    app_dir: "/home/admin/projet_ansible"

  tasks:
    - name: Clone Project
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        update: yes
        force: no

    - name: Update repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        update: yes
        accept_hostkey: yes

    - name: Lancer Docker
      shell: docker-compose up -d
      args:
          chdir: "{{ app_dir }}"