name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt install ansible -y

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Replace SERVER_IP in Ansible inventory
        run: |
          sed -i "s|{{ SERVER_IP }}|${{ secrets.SSH_HOST }}|g" ./ansible/inventory

      - name: Launch playbook
        run: |
          ansible-playbook -i ./ansible/inventory ./ansible/install.yml --private-key ~/.ssh/id_rsa